import {v4 as uuid} from "uuid";

const product = [
  {
    id: uuid(),
    imgSrc:
      "https://rukminim1.flixcart.com/image/660/792/ktizdzk0/sweatshirt/i/g/q/m-ha5641-adidas-original-imag6ux96efpm2k8.jpeg",
    title: "Full Sleeve Sweatshirt",
    oldPrice: 1500,
    newPrice: 999,
    discount: 39,
    rating: 4.5,
    isOutOfStock: false,
    category: "men",
    brand: "adidas",
    size: "medium",
    count: 1,
  },
  {
    id: uuid(),
    imgSrc:
      "https://rukminim1.flixcart.com/image/660/792/l5iid8w0/t-shirt/l/g/6/s-hd9379-adidas-original-imagg6d3bjt8hkg9.jpeg",
    title: "Women Round Neck",
    oldPrice: 1200,
    newPrice: 799,
    discount: 39,
    rating: 4.5,
    isOutOfStock: false,
    category: "women",
    brand: "adidas",
    size: "small",
    count: 1,
  },
  {
    id: uuid(),
    imgSrc:
      "https://rukminim1.flixcart.com/image/660/792/l4vnbm80/t-shirt/c/e/q/m-askporgfp82490-new-allen-solly-original-imagfzk7h3zccp4k.jpeg",
    title: "Men White Polo",
    oldPrice: 899,
    newPrice: 699,
    discount: 39,
    rating: 4.5,
    isOutOfStock: false,
    category: "men",
    brand: "allenSolly",
    size: "medium",
    count: 1,
  },
  {
    id: uuid(),
    imgSrc:
      "https://rukminim1.flixcart.com/image/660/792/kosxzm80/t-shirt/e/h/n/xl-ahkccrgpt85701-allen-solly-original-imag36hfu2ayy3m3.jpeg",
    title: "Solid Women Round Nec",
    oldPrice: 699,
    newPrice: 499,
    discount: 39,
    rating: 4.5,
    isOutOfStock: false,
    category: "women",
    brand: "allenSolly",
    size: "small",
    count: 0,
  },
  {
    id: uuid(),
    imgSrc:
      "https://rukminim1.flixcart.com/image/660/792/kfvfwy80-0/shirt/o/g/4/46-aszsh0559-arrow-original-imafw8hbffrgxc4f.jpeg",
    title: "Men Checks Shirt",
    oldPrice: 2000,
    newPrice: 1200,
    discount: 39,
    rating: 4.5,
    isOutOfStock: false,
    category: "men",
    brand: "arrow",
    size: "large",
    count: 0,
  },
  {
    id: uuid(),
    imgSrc:
      "https://rukminim1.flixcart.com/image/660/792/jkbguq80/shirt/j/n/h/s-awvsh6022blue-arrow-original-imaf7p55ydjjkeuq.jpeg",
    title: "Women Solid Shirt",
    oldPrice: 2000,
    newPrice: 1200,
    discount: 39,
    rating: 4.5,
    isOutOfStock: false,
    category: "women",
    brand: "arrow",
    size: "large",
    count: 0,
  },
];

export {product};
