import {v4 as uuid} from "uuid";
import {adidas1, adidas2, allen1, allen2, arrow1, arrow2} from "./images";

const product = [
  {
    id: uuid(),
    imgSrc: adidas1,
    title: "Full Sleeve Sweatshirt",
    oldPrice: 1500,
    newPrice: 999,
    discount: 39,
    rating: 4.5,
    isOutOfStock: false,
    category: "men",
    brand: "adidas",
    size: "medium",
  },
  {
    id: uuid(),
    imgSrc: adidas2,
    title: "Women Round Neck",
    oldPrice: 1200,
    newPrice: 799,
    discount: 39,
    rating: 4.5,
    isOutOfStock: false,
    category: "women",
    brand: "adidas",
    size: "small",
  },
  {
    id: uuid(),
    imgSrc: allen1,
    title: "Men White Polo",
    oldPrice: 899,
    newPrice: 699,
    discount: 39,
    rating: 4.5,
    isOutOfStock: false,
    category: "men",
    brand: "allenSolly",
    size: "medium",
  },
  {
    id: uuid(),
    imgSrc: allen2,
    title: "Solid Women Round Nec",
    oldPrice: 699,
    newPrice: 499,
    discount: 39,
    rating: 4.5,
    isOutOfStock: false,
    category: "women",
    brand: "allenSolly",
    size: "small",
  },
  {
    id: uuid(),
    imgSrc: arrow1,
    title: "Men Checks Shirt",
    oldPrice: 2000,
    newPrice: 1200,
    discount: 39,
    rating: 4.5,
    isOutOfStock: false,
    category: "men",
    brand: "arrow",
    size: "large",
  },
  {
    id: uuid(),
    imgSrc: arrow2,
    title: "Women Solid Shirt",
    oldPrice: 2000,
    newPrice: 1200,
    discount: 39,
    rating: 4.5,
    isOutOfStock: false,
    category: "women",
    brand: "arrow",
    size: "large",
  },
];

export {product};
